In [1]:
import matplotlib.pyplot as py
import matplotlib.image as im
import pandas as pd
import numpy as np
import os

In [2]:
x=[]
y=[]
k=0
for i in os.listdir("Train"):
    l = np.zeros(10)
    l[k] = 1
    for j in os.listdir("Train/"+i):
        a = im.imread("Train/"+i+"/"+j)
        if a is not None:
            x.append(a)
            y.append(l)
    k=k+1
x = np.array(x)
y = np.array(y)
print(x)
print(y)

[[[131 120 126 ... 123 124 119]
  [128 125 120 ... 131 127 126]
  [134 130 128 ... 126 125 124]
  ...
  [ 43  94  82 ...  66  70  66]
  [ 84  33  95 ...  63  75  64]
  [101  87  86 ...  69  61  20]]

 [[ 60  59  62 ...  49  49  49]
  [ 64  63  66 ...  52  52  52]
  [ 70  68  69 ...  56  56  55]
  ...
  [ 68  70  67 ...  52  54  57]
  [ 67  68  66 ...  52  56  55]
  [ 67  67  64 ...  53  52  53]]

 [[ 59  57 106 ...  66  68  62]
  [ 60  99 104 ...  69  66  72]
  [110 108 107 ...  73  72  75]
  ...
  [ 88  86  86 ...  83  83  84]
  [ 80  80  79 ...  75  75  76]
  [ 78  79  79 ...  73  74  75]]

 ...

 [[ 51  61 172 ...  45  44  46]
  [ 50  56 161 ...  45  44  45]
  [ 57  45 154 ...  47  45  46]
  ...
  [132 126 129 ...  96  46  43]
  [129 134 127 ...  88  49  46]
  [ 65 115 131 ...  66  51  53]]

 [[123 123 124 ... 122 123 123]
  [122 122 124 ... 124 124 123]
  [126 122 121 ... 122 122 121]
  ...
  [ 97  91  98 ...  95  97  74]
  [ 99 100  97 ...  83 106  95]
  [ 95 104  97 ...  71 103 1

In [3]:
xtest=[]
ytest=[]
k=0
for i in os.listdir("Test"):
    for j in os.listdir("Test/"+i):
        a = im.imread("Test/"+i+"/"+j)
        if a is not None:
            xtest.append(a)
            ytest.append(k)
    k=k+1
xtest = np.array(xtest)
ytest=np.array(ytest)
print(xtest)

[[[148 143 155 ... 142 140 138]
  [147 103 157 ... 143 143 143]
  [103 158 161 ... 140 142 143]
  ...
  [126 119 131 ...  94 100 100]
  [ 81 119 127 ... 105  96  97]
  [128 123 128 ...  95 100  91]]

 [[ 66  64  63 ...  45  42  37]
  [ 65  64  64 ...  82  39  42]
  [ 63  64  64 ...  79  38  45]
  ...
  [138 142 126 ... 113 114 120]
  [141 132 139 ... 114 114 120]
  [139 142 133 ... 116 115 121]]

 [[105 105 106 ... 103 102  86]
  [101 102 103 ...  93 110 126]
  [102 102 103 ... 119 131 106]
  ...
  [101  98  97 ...  27 142 152]
  [100 105 100 ...  36 157 160]
  [ 97 102  98 ...  32 153 157]]

 ...

 [[ 63  68  69 ...  65  66  66]
  [ 65  67  67 ...  69  46  87]
  [ 69  67  64 ...  87  96  89]
  ...
  [ 25  27  27 ...  22  25  26]
  [ 28  29  28 ...  72  69  38]
  [ 29  30  28 ...  66  78  71]]

 [[116 112 114 ... 113 117 115]
  [111 114 114 ... 110 112 126]
  [117 115 111 ...  79 108 140]
  ...
  [ 84  54  52 ...  76   9  17]
  [ 83  56  56 ...  77  16  16]
  [ 83  54  54 ...  85  54  

In [4]:
x = x/ 255
xtest = xtest / 255
print(x)

[[[0.51372549 0.47058824 0.49411765 ... 0.48235294 0.48627451 0.46666667]
  [0.50196078 0.49019608 0.47058824 ... 0.51372549 0.49803922 0.49411765]
  [0.5254902  0.50980392 0.50196078 ... 0.49411765 0.49019608 0.48627451]
  ...
  [0.16862745 0.36862745 0.32156863 ... 0.25882353 0.2745098  0.25882353]
  [0.32941176 0.12941176 0.37254902 ... 0.24705882 0.29411765 0.25098039]
  [0.39607843 0.34117647 0.3372549  ... 0.27058824 0.23921569 0.07843137]]

 [[0.23529412 0.23137255 0.24313725 ... 0.19215686 0.19215686 0.19215686]
  [0.25098039 0.24705882 0.25882353 ... 0.20392157 0.20392157 0.20392157]
  [0.2745098  0.26666667 0.27058824 ... 0.21960784 0.21960784 0.21568627]
  ...
  [0.26666667 0.2745098  0.2627451  ... 0.20392157 0.21176471 0.22352941]
  [0.2627451  0.26666667 0.25882353 ... 0.20392157 0.21960784 0.21568627]
  [0.2627451  0.2627451  0.25098039 ... 0.20784314 0.20392157 0.20784314]]

 [[0.23137255 0.22352941 0.41568627 ... 0.25882353 0.26666667 0.24313725]
  [0.23529412 0.388235

In [5]:
print(x.shape,xtest.shape)

(8000, 28, 28) (2000, 28, 28)


In [6]:
x=x.reshape(x.shape[0],-1)
xtest=xtest.reshape(xtest.shape[0],-1)
print(x,xtest)

[[0.51372549 0.47058824 0.49411765 ... 0.27058824 0.23921569 0.07843137]
 [0.23529412 0.23137255 0.24313725 ... 0.20784314 0.20392157 0.20784314]
 [0.23137255 0.22352941 0.41568627 ... 0.28627451 0.29019608 0.29411765]
 ...
 [0.2        0.23921569 0.6745098  ... 0.25882353 0.2        0.20784314]
 [0.48235294 0.48235294 0.48627451 ... 0.27843137 0.40392157 0.39215686]
 [0.2        0.18823529 0.1254902  ... 0.43137255 0.43921569 0.45098039]] [[0.58039216 0.56078431 0.60784314 ... 0.37254902 0.39215686 0.35686275]
 [0.25882353 0.25098039 0.24705882 ... 0.45490196 0.45098039 0.4745098 ]
 [0.41176471 0.41176471 0.41568627 ... 0.1254902  0.6        0.61568627]
 ...
 [0.24705882 0.26666667 0.27058824 ... 0.25882353 0.30588235 0.27843137]
 [0.45490196 0.43921569 0.44705882 ... 0.33333333 0.21176471 0.09019608]
 [0.99215686 0.99607843 0.97647059 ... 0.98039216 1.         1.        ]]


In [7]:
print(x.shape,xtest.shape)

(8000, 784) (2000, 784)


In [8]:
a = np.arange(x.shape[0])
np.random.shuffle(a)
x = x[a]
y=y[a]
print(x,y)

[[0.5254902  0.5372549  0.54117647 ... 0.67058824 0.64313725 0.65490196]
 [0.50196078 0.50588235 0.50588235 ... 0.21960784 0.23529412 0.22352941]
 [0.5254902  0.50196078 0.5254902  ... 0.60392157 0.61176471 0.60392157]
 ...
 [0.34509804 0.3372549  0.2627451  ... 0.49019608 0.62352941 0.65098039]
 [0.54117647 0.58823529 0.6        ... 0.56470588 0.56078431 0.56078431]
 [0.45490196 0.47058824 0.45882353 ... 0.22745098 0.36078431 0.50980392]] [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [9]:
x.shape

(8000, 784)

In [10]:
y.shape

(8000, 10)

In [11]:
x = x.T
x.shape

(784, 8000)

In [12]:
print(x)

[[0.5254902  0.50196078 0.5254902  ... 0.34509804 0.54117647 0.45490196]
 [0.5372549  0.50588235 0.50196078 ... 0.3372549  0.58823529 0.47058824]
 [0.54117647 0.50588235 0.5254902  ... 0.2627451  0.6        0.45882353]
 ...
 [0.67058824 0.21960784 0.60392157 ... 0.49019608 0.56470588 0.22745098]
 [0.64313725 0.23529412 0.61176471 ... 0.62352941 0.56078431 0.36078431]
 [0.65490196 0.22352941 0.60392157 ... 0.65098039 0.56078431 0.50980392]]


In [13]:
L=0.01
epochs = 10000

In [14]:
y.shape

(8000, 10)

In [15]:
w1 = np.random.normal(0,np.sqrt(2/float(300+784)),size=(300,784))
b1 = np.zeros((300,1))
w2 = np.random.normal(0,np.sqrt(2/float(200+300)),size=(200,300))
b2 = np.zeros((200,1))
w3 = np.random.normal(0,np.sqrt(2/float(100+200)),size=(100,200))
b3 = np.zeros((100,1))
w4 = np.random.normal(0,np.sqrt(2/float(50+100)),size=(50,100))
b4 = np.zeros((50,1))
w5 = np.random.normal(0,np.sqrt(2/float(10+50)),size=(10,50))
b5 = np.zeros((10,1))

In [16]:
max=0
maxa=[1,2,3,4,5,6,7,8,9,10]
while(epochs):
    z1 = w1.dot(x)+b1
    z1 = (z1 - np.mean(z1))/(np.std(z1))
    a1 = z1.copy()
    a1[a1<0] = 0
    z2 = w2.dot(a1)+b2
    z2 = (z2 - np.mean(z2))/(np.std(z2))
    a2=z2.copy()
    a2[a2<0] = 0
    z3 = w3.dot(a2)+b3
    z3 = (z3 - np.mean(z3))/(np.std(z3))
    a3 = z3.copy()
    a3[a3<0] = 0
    z4 = w4.dot(a3)+b4
    z4 = (z4 - np.mean(z4))/(np.std(z4))
    a4 = z4.copy()
    a4[a4<0] = 0
    z5 = w5.dot(a4)+b5
    z5 = (z5 - np.mean(z5))/(np.std(z5))
    a5 = z5.copy()
    a5 = np.exp(a5)/np.sum(np.exp(a5),0)
    dz5 = a5 - y.T
    dw5 = (1/8000)*np.dot(dz5,a4.T)
    db5 = (1/8000)*np.sum(dz5,1,keepdims=True)
    dz4 = np.dot(w5.T,dz5)*(np.array(z4 > 0, dtype = 'float'))
    dw4 = (1/8000)*np.dot(dz4,a3.T)
    db4 = (1/8000)*np.sum(dz4,1,keepdims=True)
    dz3 = np.dot(w4.T,dz4)*(np.array(z3 > 0, dtype = 'float'))
    dw3 = (1/8000)*np.dot(dz3,a2.T)
    db3 = (1/8000)*np.sum(dz3,1,keepdims=True)
    dz2 = np.dot(w3.T,dz3)*(np.array(z2 > 0, dtype = 'float'))
    dw2 = (1/8000)*np.dot(dz2,a1.T)
    db2 = (1/8000)*np.sum(dz2,1,keepdims=True)
    dz1 = np.dot(w2.T,dz2)*(np.array(z1 > 0, dtype = 'float'))
    dw1 = (1/8000)*np.dot(dz1,x.T)
    db1 = (1/8000)*np.sum(dz1,1,keepdims=True)
    w5 -= L*dw5
    b5 -= L*db5
    w4 -= L*dw4
    b4 -= L*db4
    w3 -= L*dw3
    b3 -= L*db3
    w2 -= L*dw2
    b2 -= L*db2
    w1 -= L*dw1
    b1 -= L*db1
    if (epochs%10==0):
        acc = np.argmax(a5,0) - np.argmax(y,1)
        acc = np.count_nonzero(acc==0)
        print(epochs,a5,acc/80)
        if (acc>max):
            max=acc
            maxa[0] = w1
            maxa[1] = b1
            maxa[2] = w2
            maxa[3] = b2
            maxa[4] = w3
            maxa[5] = b3
            maxa[6] = w4
            maxa[7] = b4
            maxa[8] = w5
            maxa[9] = b5
    epochs=epochs-1

10000 [[0.08798377 0.02511854 0.036613   ... 0.03108653 0.01602246 0.02956461]
 [0.20298703 0.10592975 0.24501095 ... 0.2528845  0.16970673 0.13827301]
 [0.16786285 0.21309215 0.13685365 ... 0.12779229 0.18898615 0.22831429]
 ...
 [0.03097413 0.06871184 0.04238765 ... 0.02917365 0.04123894 0.03897273]
 [0.01981036 0.01395204 0.01814279 ... 0.01309124 0.00937437 0.0259112 ]
 [0.05307966 0.07746729 0.0388628  ... 0.0501424  0.02520448 0.06627539]] 11.025
9990 [[0.34011162 0.07528671 0.13121635 ... 0.06452809 0.04629791 0.12939584]
 [0.08904881 0.03343238 0.11605042 ... 0.16453863 0.05879345 0.03338066]
 [0.10037987 0.22690328 0.04083083 ... 0.0537688  0.09691955 0.18029726]
 ...
 [0.01079977 0.10137178 0.03550868 ... 0.03073559 0.05260741 0.03990923]
 [0.11058821 0.07766349 0.14101213 ... 0.04905687 0.10356818 0.20694807]
 [0.05337611 0.11636037 0.04773107 ... 0.06683079 0.03038664 0.08854201]] 11.6625
9980 [[0.24632177 0.09132692 0.1270199  ... 0.06730214 0.05849772 0.11314893]
 [0.0988

In [18]:
max/80

48.0625

In [19]:
w1 = maxa[0]
b1 = maxa[1]
w2 = maxa[2]
b2 = maxa[3]
w3 = maxa[4]
b3 = maxa[5]
w4 = maxa[6]
b4 = maxa[7]
w5 = maxa[8]
b5 = maxa[9]
z1 = w1.dot(xtest.T)+b1
z1 = (z1 - np.mean(z1))/(np.std(z1))
a1 = z1.copy()
a1[a1<0] = 0
z2 = w2.dot(a1)+b2
z2 = (z2 - np.mean(z2))/(np.std(z2))
a2=z2.copy()
a2[a2<0] = 0
z3 = w3.dot(a2)+b3
z3 = (z3 - np.mean(z3))/(np.std(z3))
a3 = z3.copy()
a3[a3<0] = 0
z4 = w4.dot(a3)+b4
z4 = (z4 - np.mean(z4))/(np.std(z4))
a4 = z4.copy()
a4[a4<0] = 0
z5 = w5.dot(a4)+b5
z5 = (z5 - np.mean(z5))/(np.std(z5))
a5 = z5.copy()
a5 = np.exp(a5)/np.sum(np.exp(a5),0)
print(a5)

[[0.26170341 0.1909791  0.10583697 ... 0.06818392 0.04944465 0.05614374]
 [0.04185488 0.09582632 0.00626278 ... 0.02688391 0.12240218 0.01863433]
 [0.0375389  0.14536931 0.06674325 ... 0.07666392 0.0196715  0.00751777]
 ...
 [0.03162836 0.08028297 0.03498765 ... 0.04486701 0.02440323 0.20842081]
 [0.05138116 0.03511045 0.07932763 ... 0.17079223 0.18581905 0.13621818]
 [0.22146687 0.02073412 0.01622824 ... 0.05820957 0.43340537 0.12430635]]


In [20]:
a5.shape

(10, 2000)

In [21]:
ytest.shape

(2000,)

In [25]:
ypred = np.argmax(a5,axis=0)

In [26]:
ypred.shape

(2000,)

In [27]:
test = ytest-ypred
acc = np.count_nonzero(test==0)
print(acc/20)

32.4
